services:
    app:
        build:
            context: .
        platform: linux/amd64
        ports:
            - 3000:3000
        command:
            - /bin/bash
            - -c
            - |
                exec uvicorn main:app --host 0.0.0.0 --port 3000 --reload --reload-dir /app
        volumes:
            - .:/app
        working_dir: /app
    fileserver:
        image: nginx:alpine
        volumes:
            - ./pmtiles:/usr/share/nginx/html
